### ISSUE TITLE
Dinosaurs continuously following in an unnatrual way- prelude to clumping 

### ISSUE THREAD

**Issue by casmorrison** [mwdossantos/squadroninteractive#455]
https://drive.google.com/file/d/1SO4_YWv963qvKRCT8AcUw_hs08HQheRw/view?usp=sharing

The video, clearly shows the stegos closely following the mamenchi, so close. It appears its like either a threat display and the mamenchi is not scared and the stegos persisted (with aggressive behaviour)and kept following. This occurred for like 30-60 minutes at least and is still in my park currently .

Even when i controlled the stego and moved it away a considerable distance from the mamanechi it returned to the mamenchi (as seem later in the video - when i controlled the dinos).  The mamenchi is too slow to outrun as when i tried controlling it even when running it wasnt fast enough ( also in the video)

It seems that the stegos are aggressive but do not actually attack the mamaenhci
the mamenchi doesn't attack the stegos but is to slow to outurn
This suggests its a threat display / threatening behaviors

This would cause clumps but is different from the sleeping clumps reported in #403 - with kentro and stego only 

Other peoples are experiencing this i believe as well

**Comment by nqwebasaurus** [comment]
In the issue #443 I proposed a possible solution to the problem by setting an extra parameter to threatening behaviour that sets a maximum distance from the point where the chase began so that once the dinosaur is far enough from the original territory it should break the chase and return from where it started.
This should avoid the problem or at least make it less common.

**Comment by hannasue** [comment]
I think your solution would be an excellent way to help thank you nqwebasaurus
